export const VehicleData: IVehicleData[] = [
  {
    connected: true,
    Selected_VIN: "1FTEW1EP1MFA48206",
    Vehicle_Information: {
      Vehicle_Description: "2021 F150",
      Version_Series: "XLT SERIES",
      Paint_Color: "AGATE BLACK METALLIC",
      Body_Style: "Crew Cab",
      Drive_Type: "4 WHL L/H PART TIME DRIVE",
      PaintCode: "UM",
      Engine: "2.7L DOHC 4V DI GT V6 GAS",
      Axle_Ratio: "3.55 Ratio",
      Gross_Vehicle_Weight: "6600 LB. GVW",
      Transmission: "10 Speed Auto Transmission (10R80)",
      Fuel_Type: "Gasoline",
      Wheel_Size: '18 X 7.5" Chrome Wheel',
      Tire: "275/65R 18 A/T OWL",
      Sync_Version: "GEN1",
      VHR_Activated: "",
    },
    Vehicle_Status: {
      Last_Vehicle_Status_Update: "15-October-2024 10:51 AM",
      Odometer: "25850 Miles",
      Fuel_Level: "72%",
      Fuel_Range: "437 Miles to empty",
      Tire_Pressures: {
        Front_Left: "36",
        Front_Right: "36",
        Rear_Left: "35",
        Rear_Right: "35",
      },
      Oil_Life_Remaining: "77%",
      Battery_State_of_Charge: "80%",
      Battery_Voltage: "80%",
    },
    DTC_Codes: [
      {
        Date: "2024-10-15",
        Time: " 09:42 AM",
        Module: "ABS",
        DTC_Code: "U3000",
        Failure_Type: "49",
        Description: "Control Module",
      },
      {
        Date: "2024-10-14",
        Time: " 09:15 AM",
        Module: "GWM",
        DTC_Code: "U2404",
        Failure_Type: "92",
        Description: "Ethernet Failure With Image Processing Module 'A' (IPMA)",
      },
      {
        Date: "2024-10-14",
        Time: " 06:25 AM",
        Module: "ABS",
        DTC_Code: "U3000",
        Failure_Type: "49",
        Description: "Control Module",
      },
      {
        Date: "2024-10-14",
        Time: " 04:38 AM",
        Module: "GWM",
        DTC_Code: "U2404",
        Failure_Type: "92",
        Description: "Ethernet Failure With Image Processing Module 'A' (IPMA)",
      },
      {
        Date: "2024-10-13",
        Time: " 06:10 PM",
        Module: "ABS",
        DTC_Code: "U3000",
        Failure_Type: "49",
        Description: "Control Module",
      },
      {
        Date: "2024-10-10",
        Time: " 08:10 PM",
        Module: "GWM",
        DTC_Code: "U2404",
        Failure_Type: "92",
        Description: "Ethernet Failure With Image Processing Module 'A' (IPMA)",
      },
      {
        Date: "2024-10-09",
        Time: " 12:24 PM",
        Module: "ABS",
        DTC_Code: "U3000",
        Failure_Type: "49",
        Description: "Control Module",
      },
      {
        Date: "2024-10-09",
        Time: " 11:06 AM",
        Module: "GWM",
        DTC_Code: "U2404",
        Failure_Type: "92",
        Description: "Ethernet Failure With Image Processing Module 'A' (IPMA)",
      },
      {
        Date: "2024-10-09",
        Time: " 05:50 AM",
        Module: "ABS",
        DTC_Code: "U3000",
        Failure_Type: "49",
        Description: "Control Module",
      },
      {
        Date: "2024-10-08",
        Time: " 07:42 AM",
        Module: "ABS",
        DTC_Code: "U3000",
        Failure_Type: "49",
        Description: "Control Module",
      },
      {
        Date: "2024-10-08",
        Time: " 05:23 AM",
        Module: "GWM",
        DTC_Code: "U2404",
        Failure_Type: "92",
        Description: "Ethernet Failure With Image Processing Module 'A' (IPMA)",
      },
      {
        Date: "2024-10-07",
        Time: " 04:37 PM",
        Module: "ABS",
        DTC_Code: "U3000",
        Failure_Type: "49",
        Description: "Control Module",
      },
      {
        Date: "2024-10-05",
        Time: " 01:47 PM",
        Module: "GWM",
        DTC_Code: "U2404",
        Failure_Type: "92",
        Description: "Ethernet Failure With Image Processing Module 'A' (IPMA)",
      },
      {
        Date: "2024-10-05",
        Time: " 09:36 AM",
        Module: "ABS",
        DTC_Code: "U3000",
        Failure_Type: "49",
        Description: "Control Module",
      },
      {
        Date: "2024-10-01",
        Time: " 08:53 AM",
        Module: "ABS",
        DTC_Code: "U3000",
        Failure_Type: "49",
        Description: "Control Module",
      },
      {
        Date: "2024-10-01",
        Time: " 08:23 AM",
        Module: "DDM",
        DTC_Code: "B12DC",
        Failure_Type: "21",
        Description: "Front Window Motion/Position Sensor",
      },
      {
        Date: "2024-10-01",
        Time: " 05:30 AM",
        Module: "DDM",
        DTC_Code: "B12DC",
        Failure_Type: "21",
        Description: "Front Window Motion/Position Sensor",
      },
      {
        Date: "2024-09-29",
        Time: " 07:42 AM",
        Module: "GWM",
        DTC_Code: "U2404",
        Failure_Type: "92",
        Description: "Ethernet Failure With Image Processing Module 'A' (IPMA)",
      },
      {
        Date: "2024-09-29",
        Time: " 06:49 AM",
        Module: "ABS",
        DTC_Code: "U3000",
        Failure_Type: "49",
        Description: "Control Module",
      },
      {
        Date: "2024-09-26",
        Time: " 05:48 AM",
        Module: "GWM",
        DTC_Code: "U2404",
        Failure_Type: "92",
        Description: "Ethernet Failure With Image Processing Module 'A' (IPMA)",
      },
      {
        Date: "2024-09-25",
        Time: " 08:23 PM",
        Module: "ABS",
        DTC_Code: "U3000",
        Failure_Type: "49",
        Description: "Control Module",
      },
      {
        Date: "2024-09-23",
        Time: " 05:33 AM",
        Module: "GWM",
        DTC_Code: "U2404",
        Failure_Type: "92",
        Description: "Ethernet Failure With Image Processing Module 'A' (IPMA)",
      },
      {
        Date: "2024-09-22",
        Time: " 11:13 AM",
        Module: "ABS",
        DTC_Code: "U3000",
        Failure_Type: "49",
        Description: "Control Module",
      },
      {
        Date: "2024-09-21",
        Time: " 12:17 PM",
        Module: "ABS",
        DTC_Code: "U3000",
        Failure_Type: "49",
        Description: "Control Module",
      },
      {
        Date: "2024-09-18",
        Time: " 05:42 PM",
        Module: "GWM",
        DTC_Code: "U2404",
        Failure_Type: "92",
        Description: "Ethernet Failure With Image Processing Module 'A' (IPMA)",
      },
      {
        Date: "2024-09-18",
        Time: " 05:40 AM",
        Module: "ABS",
        DTC_Code: "U3000",
        Failure_Type: "49",
        Description: "Control Module",
      },
      {
        Date: "2024-09-17",
        Time: " 09:40 AM",
        Module: "GWM",
        DTC_Code: "U2404",
        Failure_Type: "92",
        Description: "Ethernet Failure With Image Processing Module 'A' (IPMA)",
      },
      {
        Date: "2024-09-17",
        Time: " 09:33 AM",
        Module: "ABS",
        DTC_Code: "U3000",
        Failure_Type: "49",
        Description: "Control Module",
      },
      {
        Date: "2024-09-17",
        Time: " 08:17 AM",
        Module: "GWM",
        DTC_Code: "U2404",
        Failure_Type: "92",
        Description: "Ethernet Failure With Image Processing Module 'A' (IPMA)",
      },
      {
        Date: "2024-09-17",
        Time: " 07:47 AM",
        Module: "PCM",
        DTC_Code: "P0316",
        Failure_Type: "00",
        Description:
          "Engine Misfire Detected on Startup (First 1000 Revolutions)",
      },
      {
        Date: "2024-09-13",
        Time: " 02:16 PM",
        Module: "GWM",
        DTC_Code: "U2404",
        Failure_Type: "92",
        Description: "Ethernet Failure With Image Processing Module 'A' (IPMA)",
      },
      {
        Date: "2024-09-13",
        Time: " 10:25 AM",
        Module: "ABS",
        DTC_Code: "U3000",
        Failure_Type: "49",
        Description: "Control Module",
      },
      {
        Date: "2024-09-12",
        Time: " 09:42 AM",
        Module: "GWM",
        DTC_Code: "U2404",
        Failure_Type: "92",
        Description: "Ethernet Failure With Image Processing Module 'A' (IPMA)",
      },
      {
        Date: "2024-09-12",
        Time: " 07:20 AM",
        Module: "ABS",
        DTC_Code: "U3000",
        Failure_Type: "49",
        Description: "Control Module",
      },
      {
        Date: "2024-09-09",
        Time: " 05:41 AM",
        Module: "ABS",
        DTC_Code: "U3000",
        Failure_Type: "49",
        Description: "Control Module",
      },
      {
        Date: "2024-09-02",
        Time: " 03:17 PM",
        Module: "PCM",
        DTC_Code: "P0316",
        Failure_Type: "00",
        Description:
          "Engine Misfire Detected on Startup (First 1000 Revolutions)",
      },
      {
        Date: "2024-09-02",
        Time: " 01:37 PM",
        Module: "PCM",
        DTC_Code: "P0316",
        Failure_Type: "00",
        Description:
          "Engine Misfire Detected on Startup (First 1000 Revolutions)",
      },
      {
        Date: "2024-08-30",
        Time: " 09:16 AM",
        Module: "GWM",
        DTC_Code: "U2404",
        Failure_Type: "92",
        Description: "Ethernet Failure With Image Processing Module 'A' (IPMA)",
      },
      {
        Date: "2024-08-30",
        Time: " 08:58 AM",
        Module: "ABS",
        DTC_Code: "U3000",
        Failure_Type: "49",
        Description: "Control Module",
      },
      {
        Date: "2024-08-29",
        Time: " 05:24 AM",
        Module: "GWM",
        DTC_Code: "U2404",
        Failure_Type: "92",
        Description: "Ethernet Failure With Image Processing Module 'A' (IPMA)",
      },
      {
        Date: "2024-08-28",
        Time: " 01:37 PM",
        Module: "BCM",
        DTC_Code: "B1533",
        Failure_Type: "08",
        Description: "Headlamp Switch Module",
      },
      {
        Date: "2024-08-26",
        Time: " 05:22 AM",
        Module: "BCM",
        DTC_Code: "B1533",
        Failure_Type: "08",
        Description: "Headlamp Switch Module",
      },
      {
        Date: "2024-08-25",
        Time: " 09:15 AM",
        Module: "GWM",
        DTC_Code: "U2404",
        Failure_Type: "92",
        Description: "Ethernet Failure With Image Processing Module 'A' (IPMA)",
      },
      {
        Date: "2024-08-25",
        Time: " 08:58 AM",
        Module: "ABS",
        DTC_Code: "U3000",
        Failure_Type: "49",
        Description: "Control Module",
      },
      {
        Date: "2024-08-25",
        Time: " 05:51 AM",
        Module: "GWM",
        DTC_Code: "U2404",
        Failure_Type: "92",
        Description: "Ethernet Failure With Image Processing Module 'A' (IPMA)",
      },
      {
        Date: "2024-08-23",
        Time: " 10:58 AM",
        Module: "ABS",
        DTC_Code: "U3000",
        Failure_Type: "49",
        Description: "Control Module",
      },
      {
        Date: "2024-08-20",
        Time: " 10:07 AM",
        Module: "GWM",
        DTC_Code: "U2404",
        Failure_Type: "92",
        Description: "Ethernet Failure With Image Processing Module 'A' (IPMA)",
      },
      {
        Date: "2024-08-20",
        Time: " 09:50 AM",
        Module: "ABS",
        DTC_Code: "U3000",
        Failure_Type: "49",
        Description: "Control Module",
      },
      {
        Date: "2024-08-18",
        Time: " 09:53 AM",
        Module: "GWM",
        DTC_Code: "U2404",
        Failure_Type: "92",
        Description: "Ethernet Failure With Image Processing Module 'A' (IPMA)",
      },
      {
        Date: "2024-08-17",
        Time: " 11:14 AM",
        Module: "ABS",
        DTC_Code: "U3000",
        Failure_Type: "49",
        Description: "Control Module",
      },
      {
        Date: "2024-08-17",
        Time: " 06:04 AM",
        Module: "GWM",
        DTC_Code: "U2404",
        Failure_Type: "92",
        Description: "Ethernet Failure With Image Processing Module 'A' (IPMA)",
      },
      {
        Date: "2024-08-16",
        Time: " 10:58 AM",
        Module: "ABS",
        DTC_Code: "U3003",
        Failure_Type: "16",
        Description: "Battery_Voltage",
      },
    ],
  },
  {
    connected: true,
    Selected_VIN: "1FTFW1E53PKE76311",
    Vehicle_Information: {
      Vehicle_Description: "2023 F150",
      Version_Series: "XLT SERIES",
      Paint_Color: "Oxford White Solid C/C",
      Body_Style: "Crew Cab",
      Drive_Type: "4 WHL L/H PART TIME DRIVE",
      PaintCode: "YZ",
      Engine: "5.0L Coyote",
      Axle_Ratio: "3.31 Ratio",
      Gross_Vehicle_Weight: "7050 LB. GVW",
      Transmission: "10 Speed Auto Transmission (10R80)",
      Fuel_Type: "Flex Fuel",
      Wheel_Size: "18 X 8.5 ALUMINUM WHL STYLE 4",
      Tire: "275/65R 18 A/T BSW #2",
      Sync_Version: "GEN4",
      VHR_Activated: "",
    },
    Vehicle_Status: {
      Last_Vehicle_Status_Update: "14-October-2024 03:54 PM",
      Odometer: "8080 Miles",
      Fuel_Level: "23%",
      Fuel_Range: "116 Miles to empty",
      Tire_Pressures: {
        Front_Left: "34",
        Front_Right: "33",
        Rear_Left: "32",
        Rear_Right: "31",
      },
      Oil_Life_Remaining: "83%",
      Battery_State_of_Charge: "67%",
      Battery_Voltage: "67%",
    },
    DTC_Codes: [
      {
        Date: "2024-09-07",
        Time: " 07:41 PM",
        Module: "",
        DTC_Code: "",
        Failure_Type: "",
        Description: "",
      },
      {
        Date: "2024-08-20",
        Time: " 05:00 PM",
        Module: "IPMA",
        DTC_Code: "B1578",
        Failure_Type: "89",
        Description: "Digital Park Assist Camera Vision System",
      },
    ],
  },
  {
    connected: true,
    Selected_VIN: "1FTFW5LD4RFB52751",
    Vehicle_Information: {
      Vehicle_Description: "2024 F150",
      Version_Series: "LARIAT SERIES",
      Paint_Color: "AGATE BLACK METALLIC",
      Body_Style: "Crew Cab",
      Drive_Type: "4 WHL L/H PART TIME DRIVE",
      PaintCode: "UM",
      Engine: "3.5L V6",
      Axle_Ratio: "3.73 Ratio",
      Gross_Vehicle_Weight: "7400 LB. GVW",
      Transmission: "MOD HYBRD TRNAXLE-A10R80-MHT-X",
      Fuel_Type: "Hybrid",
      Wheel_Size: "",
      Tire: "275/50/22 A/S BSW #2",
      Sync_Version: "GEN4",
      VHR_Activated: "",
    },
    Vehicle_Status: {
      Last_Vehicle_Status_Update: "15-October-2024 04:59 PM",
      Odometer: "3076 Miles",
      Fuel_Level: "25%",
      Fuel_Range: "167 Miles to empty",
      Tire_Pressures: {
        Front_Left: "42",
        Front_Right: "42",
        Rear_Left: "40",
        Rear_Right: "41",
      },
      Oil_Life_Remaining: "75%",
      Battery_State_of_Charge: "93%",
      Battery_Voltage: "93%",
    },
    DTC_Codes: [
      {
        Date: "2024-09-05",
        Time: " 10:55 AM",
        Module: "BCM",
        DTC_Code: "B16A7",
        Failure_Type: "12",
        Description: "Circuit Short To Battery",
      },
      {
        Date: "2024-09-15",
        Time: " 11:45 AM",
        Module: "HCM",
        DTC_Code: "U211B",
        Failure_Type: "87",
        Description: "Control Module Message Authentication: Missing Message",
      },
      {
        Date: "2024-10-25",
        Time: " 01:45 PM",
        Module: "IPMA",
        DTC_Code: "B1385",
        Failure_Type: "68",
        Description: "Lane Keeping Aid System: Event Information",
      },
      {
        Date: "2024-11-01",
        Time: " 02:25 PM",
        Module: "HCM",
        DTC_Code: "B14D9",
        Failure_Type: "01",
        Description: "",
      },
      {
        Date: "2024-05-30",
        Time: " 04:35 PM",
        Module: "ABS",
        DTC_Code: "C060A",
        Failure_Type: "00",
        Description: "Park Brake Switch Stuck: No Sub Type Information",
      },
      {
        Date: "2024-07-12",
        Time: " 06:35 PM",
        Module: "HCM",
        DTC_Code: "U211B",
        Failure_Type: "87",
        Description: "Control Module Message Authentication: Missing Message",
      },
      {
        Date: "2024-10-15",
        Time: " 04:56 PM",
        Module: "IPC",
        DTC_Code: "U053B",
        Failure_Type: "82",
        Description: "Invalid Data Received From Image Processing Module 'A'",
      },
      {
        Date: "2024-10-10",
        Time: " 08:30 PM",
        Module: "IPC",
        DTC_Code: "U053B",
        Failure_Type: "82",
        Description: "Invalid Data Received From Image Processing Module 'A'",
      },
      {
        Date: "2024-10-07",
        Time: " 01:14 PM",
        Module: "HCM",
        DTC_Code: "U211B",
        Failure_Type: "87",
        Description: "Control Module Message Authentication",
      },
      {
        Date: "2024-10-06",
        Time: " 04:19 PM",
        Module: "HCM",
        DTC_Code: "U211B",
        Failure_Type: "87",
        Description: "Control Module Message Authentication",
      },
      {
        Date: "2024-09-25",
        Time: " 07:29 PM",
        Module: "IPC",
        DTC_Code: "U053B",
        Failure_Type: "82",
        Description: "Invalid Data Received From Image Processing Module 'A'",
      },
      {
        Date: "2024-09-24",
        Time: " 08:13 AM",
        Module: "",
        DTC_Code: "",
        Failure_Type: "",
        Description: "",
      },
      {
        Date: "2024-09-24",
        Time: " 08:10 AM",
        Module: "",
        DTC_Code: "",
        Failure_Type: "",
        Description: "",
      },
      {
        Date: "2024-09-24",
        Time: " 08:08 AM",
        Module: "",
        DTC_Code: "",
        Failure_Type: "",
        Description: "",
      },
      {
        Date: "2024-09-23",
        Time: " 03:15 PM",
        Module: "HCM",
        DTC_Code: "U211B",
        Failure_Type: "87",
        Description: "Control Module Message Authentication",
      },
      {
        Date: "2024-09-19",
        Time: " 03:34 PM",
        Module: "HCM",
        DTC_Code: "U211B",
        Failure_Type: "87",
        Description: "Control Module Message Authentication",
      },
      {
        Date: "2024-09-15",
        Time: " 09:42 AM",
        Module: "IPMA",
        DTC_Code: "B1385",
        Failure_Type: "68",
        Description: "Lane Keeping Aid System",
      },
      {
        Date: "2024-09-13",
        Time: " 09:33 AM",
        Module: "IPMA",
        DTC_Code: "B1385",
        Failure_Type: "68",
        Description: "Lane Keeping Aid System",
      },
      {
        Date: "2024-09-12",
        Time: " 04:11 PM",
        Module: "HCM",
        DTC_Code: "U211B",
        Failure_Type: "87",
        Description: "Control Module Message Authentication",
      },
      {
        Date: "2024-09-10",
        Time: " 02:49 PM",
        Module: "IPMA",
        DTC_Code: "B1578",
        Failure_Type: "89",
        Description: "Digital Park Assist Camera Vision System",
      },
      {
        Date: "2024-09-09",
        Time: " 01:39 PM",
        Module: "IPMA",
        DTC_Code: "B1578",
        Failure_Type: "89",
        Description: "Digital Park Assist Camera Vision System",
      },
      {
        Date: "2024-09-08",
        Time: " 04:11 PM",
        Module: "IPMA",
        DTC_Code: "B1385",
        Failure_Type: "68",
        Description: "Lane Keeping Aid System",
      },
      {
        Date: "2024-09-08",
        Time: " 09:24 AM",
        Module: "IPMA",
        DTC_Code: "B1385",
        Failure_Type: "68",
        Description: "Lane Keeping Aid System",
      },
      {
        Date: "2024-09-05",
        Time: " 12:39 AM",
        Module: "PCM",
        DTC_Code: "U3523",
        Failure_Type: "00",
        Description: "High Voltage System Interlock Circuit 'F' Low",
      },
      {
        Date: "2024-09-01",
        Time: " 12:31 PM",
        Module: "HCM",
        DTC_Code: "U211B",
        Failure_Type: "87",
        Description: "Control Module Message Authentication",
      },
      {
        Date: "2024-08-31",
        Time: " 02:02 PM",
        Module: "HCM",
        DTC_Code: "U211B",
        Failure_Type: "87",
        Description: "Control Module Message Authentication",
      },
      {
        Date: "2024-08-31",
        Time: " 09:58 AM",
        Module: "HCM",
        DTC_Code: "U211B",
        Failure_Type: "87",
        Description: "Control Module Message Authentication",
      },
    ],
  },
  {
    connected: true,
    Selected_VIN: "1FTVW1ELXPWG02702",
    Vehicle_Information: {
      Vehicle_Description: "2023 F150",
      Version_Series: "XLT SERIES",
      Paint_Color: "ANTIMATTER BLUE/SIGNATURE NAVY",
      Body_Style: "Crew Cab",
      Drive_Type: "4 WHL L/H PART TIME DRIVE",
      PaintCode: "HX",
      Engine: "BATTERY ELECTRIC MOTOR B4A63L",
      Axle_Ratio: "ELECTRIC DRIVE",
      Gross_Vehicle_Weight: "8250 LB. GVW",
      Transmission: "1 Speed Transmission",
      Fuel_Type: "Electric",
      Wheel_Size: "8.5 X 18 BASE ALLOY WHEEL",
      Tire: "275/65R 18 A/T",
      Sync_Version: "GEN4",
      VHR_Activated: "",
    },
    Vehicle_Status: undefined,
    DTC_Codes: [],
  },
  {
    connected: true,
    Selected_VIN: "1FTFW1E85MFA63398",
    Vehicle_Information: {
      Vehicle_Description: "2021 F150",
      Version_Series: "XLT SERIES",
      Paint_Color: "LUCID RED TC/RED CARPET TC",
      Body_Style: "Crew Cab",
      Drive_Type: "4 WHL L/H PART TIME DRIVE",
      PaintCode: "D4",
      Engine: "3.5L CYCLON-D4- G-DI-TIVCT-UPG",
      Axle_Ratio: "3.31 Ratio",
      Gross_Vehicle_Weight: "7150 LB. GVW",
      Transmission: "10 Speed Auto Transmission (10R80)",
      Fuel_Type: "Gasoline",
      Wheel_Size: '18 X 7.5" Chrome Wheel',
      Tire: "LT 265/70/18 A/T OWL",
      Sync_Version: "GEN4",
      VHR_Activated: "",
    },
    Vehicle_Status: {
      Last_Vehicle_Status_Update: "25-October-2024 05:37 AM",
      Odometer: "42701 Miles",
      Fuel_Level: "20%",
      Fuel_Range: "115 Miles to empty",
      Tire_Pressures: {
        Front_Left: "37",
        Front_Right: "37",
        Rear_Left: "40",
        Rear_Right: "38",
      },
      Oil_Life_Remaining: "29%",
      Battery_State_of_Charge: "77%",
      Battery_Voltage: "77%",
    },
    DTC_Codes: [
      {
        Date: "2024-10-25",
        Time: " 04:16 AM",
        Module: "GWM",
        DTC_Code: "U2404",
        Failure_Type: "92",
        Description: "Ethernet Failure With Image Processing Module 'A' (IPMA)",
      },
      {
        Date: "2024-10-24",
        Time: " 08:07 AM",
        Module: "IPC",
        DTC_Code: "U0554",
        Failure_Type: "00",
        Description:
          "Invalid Data Received From Accessory Protocol Interface Module 'A'",
      },
      {
        Date: "2024-10-18",
        Time: " 07:10 AM",
        Module: "GWM",
        DTC_Code: "U2404",
        Failure_Type: "92",
        Description: "Ethernet Failure With Image Processing Module 'A' (IPMA)",
      },
      {
        Date: "2024-10-18",
        Time: " 06:48 AM",
        Module: "IPC",
        DTC_Code: "U0554",
        Failure_Type: "00",
        Description:
          "Invalid Data Received From Accessory Protocol Interface Module 'A'",
      },
      {
        Date: "2024-10-13",
        Time: " 04:35 PM",
        Module: "GWM",
        DTC_Code: "U2404",
        Failure_Type: "92",
        Description: "Ethernet Failure With Image Processing Module 'A' (IPMA)",
      },
      {
        Date: "2024-10-13",
        Time: " 01:27 PM",
        Module: "IPC",
        DTC_Code: "U0554",
        Failure_Type: "00",
        Description:
          "Invalid Data Received From Accessory Protocol Interface Module 'A'",
      },
      {
        Date: "2024-10-13",
        Time: " 01:17 PM",
        Module: "IPC",
        DTC_Code: "U0554",
        Failure_Type: "00",
        Description:
          "Invalid Data Received From Accessory Protocol Interface Module 'A'",
      },
      {
        Date: "2024-09-26",
        Time: " 10:09 AM",
        Module: "GWM",
        DTC_Code: "U2404",
        Failure_Type: "92",
        Description: "Ethernet Failure With Image Processing Module 'A' (IPMA)",
      },
      {
        Date: "2024-09-26",
        Time: " 09:48 AM",
        Module: "IPC",
        DTC_Code: "U0554",
        Failure_Type: "00",
        Description:
          "Invalid Data Received From Accessory Protocol Interface Module 'A'",
      },
      {
        Date: "2024-09-23",
        Time: " 03:41 PM",
        Module: "GWM",
        DTC_Code: "U2404",
        Failure_Type: "92",
        Description: "Ethernet Failure With Image Processing Module 'A' (IPMA)",
      },
      {
        Date: "2024-09-23",
        Time: " 01:57 PM",
        Module: "IPC",
        DTC_Code: "U0554",
        Failure_Type: "00",
        Description:
          "Invalid Data Received From Accessory Protocol Interface Module 'A'",
      },
      {
        Date: "2024-09-20",
        Time: " 03:02 PM",
        Module: "IPC",
        DTC_Code: "U0554",
        Failure_Type: "00",
        Description:
          "Invalid Data Received From Accessory Protocol Interface Module 'A'",
      },
      {
        Date: "2024-09-20",
        Time: " 11:33 AM",
        Module: "GWM",
        DTC_Code: "U2404",
        Failure_Type: "92",
        Description: "Ethernet Failure With Image Processing Module 'A' (IPMA)",
      },
      {
        Date: "2024-09-20",
        Time: " 11:13 AM",
        Module: "IPC",
        DTC_Code: "U0554",
        Failure_Type: "00",
        Description:
          "Invalid Data Received From Accessory Protocol Interface Module 'A'",
      },
      {
        Date: "2024-09-18",
        Time: " 02:17 PM",
        Module: "GWM",
        DTC_Code: "U2404",
        Failure_Type: "92",
        Description: "Ethernet Failure With Image Processing Module 'A' (IPMA)",
      },
      {
        Date: "2024-09-18",
        Time: " 11:42 AM",
        Module: "IPC",
        DTC_Code: "U0554",
        Failure_Type: "00",
        Description:
          "Invalid Data Received From Accessory Protocol Interface Module 'A'",
      },
      {
        Date: "2024-09-16",
        Time: " 12:48 PM",
        Module: "GWM",
        DTC_Code: "U2404",
        Failure_Type: "92",
        Description: "Ethernet Failure With Image Processing Module 'A' (IPMA)",
      },
      {
        Date: "2024-09-16",
        Time: " 12:15 PM",
        Module: "IPC",
        DTC_Code: "U0554",
        Failure_Type: "00",
        Description:
          "Invalid Data Received From Accessory Protocol Interface Module 'A'",
      },
      {
        Date: "2024-09-15",
        Time: " 10:29 AM",
        Module: "GWM",
        DTC_Code: "U2404",
        Failure_Type: "92",
        Description: "Ethernet Failure With Image Processing Module 'A' (IPMA)",
      },
      {
        Date: "2024-09-15",
        Time: " 10:14 AM",
        Module: "IPC",
        DTC_Code: "U0554",
        Failure_Type: "00",
        Description:
          "Invalid Data Received From Accessory Protocol Interface Module 'A'",
      },
      {
        Date: "2024-09-15",
        Time: " 09:38 AM",
        Module: "GWM",
        DTC_Code: "U2404",
        Failure_Type: "92",
        Description: "Ethernet Failure With Image Processing Module 'A' (IPMA)",
      },
      {
        Date: "2024-09-15",
        Time: " 07:49 AM",
        Module: "IPC",
        DTC_Code: "U0554",
        Failure_Type: "00",
        Description:
          "Invalid Data Received From Accessory Protocol Interface Module 'A'",
      },
    ],
  },
];

export interface IVehicleData {
  connected: boolean;
  Selected_VIN: string;
  Vehicle_Information: {
    Vehicle_Description: string;
    Version_Series: string;
    Paint_Color: string;
    Body_Style: string;
    Drive_Type: string;
    PaintCode: string;
    Engine: string;
    Axle_Ratio: string;
    Gross_Vehicle_Weight: string;
    Transmission: string;
    Fuel_Type: string;
    Wheel_Size: string;
    Tire: string;
    Sync_Version: string;
    VHR_Activated: string;
  };
  Vehicle_Status?: {
    Last_Vehicle_Status_Update: string;
    Odometer: string;
    Fuel_Level: string;
    Fuel_Range: string;
    Tire_Pressures: {
      Front_Left: string;
      Front_Right: string;
      Rear_Left: string;
      Rear_Right: string;
    };
    Oil_Life_Remaining: string;
    Battery_State_of_Charge: string;
    Battery_Voltage: string;
  };
  DTC_Codes: IDTC_CODES[];
}

export interface IDTC_CODES {
  [x: string]: any;
  Date: string;
  Time: string;
  Module: string;
  DTC_Code: string;
  Failure_Type: string;
  Description: string;
}
